//
//  ListOrdersInteractor.swift
//  CleanStore
//
//  Created by Santiago Pelaez Rua on 5/17/18.
//  Copyright (c) 2018 Santiago Peláez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListOrdersBusinessLogic
{
  func doSomething(request: ListOrders.Something.Request)
}

protocol ListOrdersDataStore
{
  //var name: String { get set }
}

class ListOrdersInteractor: ListOrdersBusinessLogic, ListOrdersDataStore
{
  var presenter: ListOrdersPresentationLogic?
  var worker: ListOrdersWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListOrders.Something.Request)
  {
    worker = ListOrdersWorker()
    worker?.doSomeWork()
    
    let response = ListOrders.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
