//
//  CreateOrderModels.swift
//  CleanStore
//
//  Created by Santiago Peláez on 5/12/18.
//  Copyright (c) 2018 Santiago Peláez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateOrder {
  // MARK: Use cases
  enum FormatExpirationDate {
    struct Request {
      var date: Date
    }
    struct Response {
      var date: Date
    }
    struct ViewModel {
      var date: String
    }
  }
}
