//
//  CreateOrderInteractor.swift
//  CleanStore
//
//  Created by Santiago Peláez on 5/12/18.
//  Copyright (c) 2018 Santiago Peláez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateOrderBusinessLogic {
  var shippingMethods: [String] { get }
}

protocol CreateOrderDataStore {
  //var name: String { get set }
}

class CreateOrderInteractor: CreateOrderBusinessLogic, CreateOrderDataStore {
  var presenter: CreateOrderPresentationLogic?
  var worker: CreateOrderWorker?
  var shippingMethods = [
    "Standard Shipping",
    "Two-Day Shipping",
    "One-Day Shipping"
  ]
}
